var a,b,s,e,t, w;
w = 'w';
a = b = 10000000;
s = new Date();
while(a--) 'qwerty'.replace('w','Q');
e = new Date();
t = (e-s) / 1000;
console.log("Using 'qwerty'.replace('w','Q'); " + 'took ' + t + ' seconds for ' + b + ' replacements ' + ((b / t) | 0) + ' replacements per second.');
w = 'w';
a = b = 10000000;
s = new Date();
while(a--) 'qwerty'.replace(/w/,'Q');
e = new Date();
t = (e-s) / 1000;
console.log("Using 'qwerty'.replace(/w/,'Q'); " + 'took ' + t + ' seconds for ' + b + ' replacements ' + ((b / t) | 0) + ' replacements per second.');
w = 'w';
a = b = 10000000;
s = new Date();
while(a--) 'qwerty'.replace(w,'Q');
e = new Date();
t = (e-s) / 1000;
console.log("Using var w = 'w'; qwerty'.replace(w ,'Q'); " + 'took ' + t + ' seconds for ' + b + ' replacements ' + ((b / t) | 0) + ' replacements per second.');
w = /w/;
a = b = 10000000;
s = new Date();
while(a--) 'qwerty'.replace('w','Q');
e = new Date();
t = (e-s) / 1000;
console.log("Using var w = /w/; qwerty'.replace(w ,'Q'); " + 'took ' + t + ' seconds for ' + b + ' replacements ' + ((b / t) | 0) + ' replacements per second.');
