[{
    "app": "Adobe Illustrator CC 2018",
    "appCode": "ILST",
    "appVersion": "22.0.0",
    "id": "com.adobe.ccx.start",
    "dirName": "/Applications/Adobe Illustrator CC 2018/Adobe Illustrator.app/Contents/Required/CEP/extensions/com.adobe.ccx.start",
    "name": "Start",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-ILST-22.0.0-com.adobe.ccx.start.log",
    "logLevel": "3 - info",
    "cepPid": "1057",
    "renderPid": "1062",
    "gpuPid": "1063",
    "commandLineParameters": ["--disable-pinch", "--no-sandbox"],
    "lang": "en-US"
}, {
    "app": "Adobe InDesign CC 2018",
    "appCode": "IDSN",
    "appVersion": "13.0",
    "id": "com.adobe.ccx.start",
    "dirName": "/Applications/Adobe InDesign CC 2018/Adobe InDesign CC 2018.app/Contents/Resources/CEP/extensions/com.adobe.ccx.start",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-IDSN-13.0-com.adobe.ccx.start.log",
    "logLevel": "3 - info",
    "cepPid": "1068",
    "renderPid": "1166",
    "gpuPid": "1115",
    "commandLineParameters": ["--disable-pinch", "--no-sandbox"],
    "lang": "en-US"
}, {
    "app": "Adobe InDesign CC 2018",
    "appCode": "IDSN",
    "appVersion": "13.0",
    "id": "com.adobe.DesignLibraries.angular",
    "dirName": "/Applications/Adobe InDesign CC 2018/Adobe InDesign CC 2018.app/Contents/Resources/CEP/extensions/com.adobe.DesignLibraries.angular",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-IDSN-13.0-com.adobe.DesignLibraries.angular.log",
    "logLevel": "3 - info",
    "cepPid": "1118",
    "renderPid": "1169",
    "gpuPid": "1155",
    "commandLineParameters": ["--disable-accelerated-video-decode", "--no-sandbox", "--enable-nodejs"],
    "lang": "en-US"
}, {
    "app": "Adobe InDesign CC 2018",
    "appCode": "IDSN",
    "appVersion": "13.0",
    "id": "com.adobe.butler.OnBoarding",
    "dirName": "/Applications/Adobe InDesign CC 2018/Adobe InDesign CC 2018.app/Contents/Resources/CEP/extensions/com.adobe.butler.OnBoarding",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-IDSN-13.0-com.adobe.butler.OnBoarding.log",
    "logLevel": "3 - info",
    "cepPid": "1132",
    "renderPid": "1170",
    "gpuPid": "1156",
    "commandLineParameters": ["--no-sandbox"],
    "lang": "en-US"
}, {
    "app": "Adobe InDesign CC 2018",
    "appCode": "IDSN",
    "appVersion": "13.0",
    "id": "com.creative-scripts.Druckbogen_Vorschau",
    "dirName": "/Library/Application Support/Adobe/CEP/extensions/com.creative-scripts.Druckbogen_Vorschau",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-IDSN-13.0-com.creative-scripts.Druckbogen_Vorschau.log",
    "logLevel": "3 - info",
    "cepPid": "1164",
    "renderPid": "1184",
    "gpuPid": "1179",
    "commandLineParameters": ["--no-sandbox", "--enable-nodejs"],
    "lang": "en-US"
}, {
    "app": "Adobe Illustrator CC 2018",
    "appCode": "ILST",
    "appVersion": "22.0.0",
    "id": "com.creative-scripts.xml.to.ai.ext",
    "dirName": "/Library/Application Support/Adobe/CEP/extensions/XML to Ai Extension",
    "name": "Creative Scripts XML to Ai",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-ILST-22.0.0-com.creative-scripts.xml.to.ai.ext.log",
    "logLevel": "3 - info",
    "cepPid": "1674",
    "renderPid": "1682",
    "gpuPid": "1685",
    "commandLineParameters": ["--no-sandbox", "--enable-nodejs"],
    "lang": "en-US"
}, {
    "app": "Adobe Illustrator CC 2018",
    "appCode": "ILST",
    "appVersion": "22.0.0",
    "id": "com.creative-scripts.test.ext",
    "dirName": "/Library/Application Support/Adobe/CEP/extensions/Creative Scripts Envision Aviation Illustrator Extension",
    "name": "Creative Scripts Illustrator Suite",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-ILST-22.0.0-com.creative-scripts.test.ext.log",
    "logLevel": "3 - info",
    "cepPid": "1675",
    "renderPid": "1680",
    "gpuPid": "1688",
    "commandLineParameters": ["--no-sandbox", "--enable-nodejs", "--mixed-context"],
    "lang": "en-US"
}, {
    "app": "Adobe Illustrator CC 2018",
    "appCode": "ILST",
    "appVersion": "22.0.0",
    "id": "com.creative-scripts.Hello-World-restart-test.1",
    "dirName": "/Library/Application Support/Adobe/CEP/extensions/Hello World",
    "name": "Hello World",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-ILST-22.0.0-com.creative-scripts.Hello-World-restart-test.1.log",
    "logLevel": "3 - info",
    "cepPid": "1676",
    "renderPid": "1681",
    "gpuPid": "1687",
    "commandLineParameters": ["--no-sandbox", "--enable-nodejs", "--mixed-context"],
    "lang": "en-US"
}, {
    "app": "Adobe Illustrator CC 2018",
    "appCode": "ILST",
    "appVersion": "22.0.0",
    "id": "com.creative-scripts.hopkins.pdf.xlsx",
    "dirName": "/Library/Application Support/Adobe/CEP/extensions/Creative Scripts Hopkins XLXS PDF Merge",
    "name": "Creative Scripts XLSX => PDF Merge",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-ILST-22.0.0-com.creative-scripts.hopkins.pdf.xlsx.log",
    "logLevel": "3 - info",
    "cepPid": "1677",
    "renderPid": "1683",
    "gpuPid": "1684",
    "commandLineParameters": ["--no-sandbox", "--enable-nodejs"],
    "lang": "en-US"
}, {
    "app": "Adobe Illustrator CC 2018",
    "appCode": "ILST",
    "appVersion": "22.0.0",
    "id": "com.adobe.illustrator.OnBoarding",
    "dirName": "/Applications/Adobe Illustrator CC 2018/Adobe Illustrator.app/Contents/Required/CEP/extensions/com.adobe.illustrator.OnBoarding",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-ILST-22.0.0-com.adobe.illustrator.OnBoarding.log",
    "logLevel": "3 - info",
    "cepPid": "1678",
    "renderPid": "1679",
    "gpuPid": "1686",
    "commandLineParameters": ["--no-sandbox"],
    "lang": "en-US"
}, {
    "app": "Adobe Illustrator CC 2018",
    "appCode": "ILST",
    "appVersion": "22.0.0",
    "id": "com.adobe.svgwriter.extension",
    "dirName": "/Applications/Adobe Illustrator CC 2018/Adobe Illustrator.app/Contents/Required/CEP/extensions/com.adobe.svgwriter",
    "name": "com.adobe.svgwriter.extension",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-ILST-22.0.0-com.adobe.svgwriter.extension.log",
    "logLevel": "3 - info",
    "cepPid": "1696",
    "renderPid": "1701",
    "commandLineParameters": ["--no-sandbox", "--enable-nodejs"],
    "lang": "en-US"
}, {
    "app": "Adobe Illustrator CC 2018",
    "appCode": "ILST",
    "appVersion": "22.0.0",
    "id": "com.creative-scripts.cstk.1",
    "dirName": "/Library/Application Support/Adobe/CEP/extensions/CSTK",
    "name": "CSTK",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-ILST-22.0.0-com.creative-scripts.cstk.1.log",
    "logLevel": "3 - info",
    "cepPid": "1698",
    "renderPid": "1700",
    "gpuPid": "1699",
    "debugPort": "localhost:9072",
    "commandLineParameters": ["--no-sandbox", "--enable-nodejs", "--mixed-context"],
    "lang": "en-US"
}, {
    "app": "Adobe InDesign CC 2018",
    "appCode": "IDSN",
    "appVersion": "13.0",
    "id": "com.creative-scripts.Hello-World-restart-test.1",
    "dirName": "/Library/Application Support/Adobe/CEP/extensions/Hello World",
    "name": "Hello World",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-IDSN-13.0-com.creative-scripts.Hello-World-restart-test.1.log",
    "logLevel": "3 - info",
    "cepPid": "2344",
    "renderPid": "2349",
    "gpuPid": "2347",
    "commandLineParameters": ["--no-sandbox", "--enable-nodejs", "--mixed-context"],
    "lang": "en-US"
}, {
    "app": "Adobe InDesign CC 2018",
    "appCode": "IDSN",
    "appVersion": "13.0",
    "id": "com.creative-scripts.hopkins.pdf.xlsx",
    "dirName": "/Library/Application Support/Adobe/CEP/extensions/Creative Scripts Hopkins XLXS PDF Merge",
    "name": "Creative Scripts XLSX => PDF Merge",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-IDSN-13.0-com.creative-scripts.hopkins.pdf.xlsx.log",
    "logLevel": "3 - info",
    "cepPid": "2346",
    "renderPid": "2350",
    "gpuPid": "2348",
    "commandLineParameters": ["--no-sandbox", "--enable-nodejs"],
    "lang": "en-US"
}, {
    "app": "Adobe InDesign CC 2018",
    "appCode": "IDSN",
    "appVersion": "13.0",
    "id": "com.creative-scripts.cstk.1",
    "dirName": "/Library/Application Support/Adobe/CEP/extensions/CSTK",
    "name": "CSTK",
    "log": "/Users/Trevor/Library/Logs/CSXS/CEPHtmlEngine8-IDSN-13.0-com.creative-scripts.cstk.1.log",
    "logLevel": "3 - info",
    "cepPid": "2354",
    "renderPid": "2356",
    "gpuPid": "2355",
    "debugPort": "localhost:9073",
    "commandLineParameters": ["--no-sandbox", "--enable-nodejs", "--mixed-context"],
    "lang": "en-US"
}]
